#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#define LOG_FILEPATH "../log.txt"

#define SPLASHSTATE_BACKGROUND_PATH "../../resources/background_splash.png"
#define SPLASHSTATE_SHOWTIME 3.0f

#define MAINMENU_BACKGROUND_PATH "XYZ"
#define MAINMENU_TITLE_PATH "XYZ"
#define MAINMENU_PLAYBUTTON_PATH "XYZ"

#define GAMESTATE_BACKGROUND_PATH "XYZ"


#endif //DEFINITIONS_H
